### ISSUE TITLE
Bug - "Unknown Error" importing Controller Blueprints in HA 2022.5

### ISSUE THREAD

**Issue by HVR88** [EPMatt/awesome-ha-blueprints#330] opened 2022-05-06 12:54 UTC
### Blueprint name

Controller - IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote

### Home Assistant Core Version

2022.5.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

"Unknown Error" is displayed when trying to import controller blueprints using the "My HomeAssistant" links.

First observed in HA 2022.5.1

### Automation YAML config

```yaml
N/A
```

### To Reproduce

1. Go to https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1524_e1810
2. Click on Import Blueprint button/link and follow pompts
3. Confirm/accept import in Home Assistant UI

### Expected behavior

Import successful and blueprint listed within the Blueprints tab/list.

### Actual Behaviour

No import takes place.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by EPMatt** [comment] 2022-05-09 22:32
Hi @HVR88,

thank you for opening an issue here. Is this happening only with the blueprint you mentioned in your comment, or can you experience the same bug with other blueprints not included in this collection?
Moreover, could you please update your HA instance to the latest version (`2022.5.3`) and see if the issue is solved?

Thank you! :)

**Comment by HVR88** [comment] 2022-05-09 22:37
Great news, seems to be working with 2022.5.3 - I had already updated this morning but haven't had any time to come back to test since first posting the issue.

Looking forward to giving these blueprints a try as I just recently picked up a few of the IKEA 5-button, on/off and Symfonisk volume button. And I also have a couple of the Aqara 6-button I want to test out with your long-press looping support.

**Comment by EPMatt** [comment] 2022-05-10 22:05
Hi @HVR88 ,

thank you for your feedback, that's great news! 🚀 

Since your issue is solved, I'm now closing this ticket. If you need any further help or you experience any other issue, please open a new ticket [here](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). I'd be glad to help and answer any of your questions.

> Looking forward to giving these blueprints a try as I just recently picked up a few of the IKEA 5-button, on/off and Symfonisk volume button. And I also have a couple of the Aqara 6-button I want to test out with your long-press looping support.

Super! I hope you'll find this project useful. Enjoy the blueprints. :)

Thank you and happy automating!

**Closed by EPMatt** 2022-05-10 22:05 UTC
Labels: bug, blueprint
