### ISSUE TITLE
[BUG] IKEA E1744 SYMFONISK Rotary Remote

### ISSUE THREAD

**Issue by ShagoY** [EPMatt/awesome-ha-blueprints#9] opened 2021-03-15 17:04 UTC
**Bug Details**

- Blueprint name: IKEA E1744 SYMFONISK Rotary Remote
- Home Assistant Core Version: 2021.3.4
- Home Assistant Installation Type: Home Assistant OS

**Description**
The "reset the text helper" part for "helper_last_controller_event" input is missing

**Additional context**
```
  # reset the text helper
  - service: 'input_text.set_value'
    data:
      entity_id: !input helper_last_controller_event
      value: ''
```

**Comment by EPMatt** [comment] 2021-03-15 18:07
Hi @ShagoY,

thank you for reporting. Where do you think this piece of code should be added?
Please point out the line/lines where you would insert it in the blueprint file.

Thanks!

**Comment by ShagoY** [comment] 2021-03-15 18:15
I just noticed that the SYMFONISK helper input did not return to NULL after a while, unlike the behavior of your other controllers.

Looking at the code, I saw that you were doing a reset.

**Comment by EPMatt** [comment] 2021-03-15 18:33
Hi @ShagoY,

The `helper_last_controller_event` input needs to be reset only when dealing with virtual double press events, like in the following case: 
https://github.com/EPMatt/awesome-ha-blueprints/blob/4625975ba85b58a5eaa74a6d3cdfdcd0201969c4/blueprints/controllers/ikea_e1743/ikea_e1743.yaml#L225-L255

Since having a "dirty" value in the helper could fire false positive double press events.

The IKEA E1744 natively exposes double and triple press events, so the helper is not needed in this case, but it's required only to understand whether a `stop` event is referred to a left or right rotation, for Zigbee2MQTT and ZHA. Howhever, this situation is different: before reading the value stored in the input, a `rotate` event must always be triggered, with the result of the helper being updated to the correct value, before being read by the next run.

For this reason, the helper reset is never performed when it is used for handling `release` or `stop` events. This is valid for all Controller blueprints, like in the following section:

https://github.com/EPMatt/awesome-ha-blueprints/blob/4625975ba85b58a5eaa74a6d3cdfdcd0201969c4/blueprints/controllers/ikea_e1743/ikea_e1743.yaml#L306-L318

Avoiding to reset the input in these situations allows to avoid a service call, a state update in the HA core and a memory write, resulting in a slight gain in performance for the blueprint. :)

I'd also like to point out that resetting the input would not allow to use the same input as helper for different Controller automations, since race conditions will still be present, and a consistent behaviour could not be guaranteed if multiple automations need to access the helper at the same time.

**Comment by EPMatt** [comment] 2021-03-25 14:48
Hi @ShagoY,

I'm closing this issue since it's not a bug related to the E1743 Controller blueprint.
If you still have any doubts or suggestions, I'd be happy to hear back from you. :) 

Thank you for your feedback!

**Closed by EPMatt** 2021-03-25 14:48 UTC
Labels: bug
