### ISSUE TITLE
Ikea E1743 only respond to short press

### ISSUE THREAD

**Issue by bkje14** [EPMatt/awesome-ha-blueprints#53] opened 2021-05-03 18:53 UTC
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: Controller - IKEA E1743 On/Off Switch & Dimmer
- Home Assistant Core Version: 2021.4.3
- Home Assistant Installation Type: Home Assistant OS

## Description\*

I had an automation configured with short, long and double clicks that have been running smoothly for weeks since i set it up.
Currently the automation only fires correctly when removing actions for the long and double clicks and only having short presses configured.
Configuring either long presses or double click actions results in errors in the execution flow. 

Below is a screen dump of the error when inspecting the flow.

## Automation YAML config\*

```yaml
alias: stue switch
description: Ikea remote som lys styring i stuen
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.stue_switch_action
    action_button_up_short:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_pct: 60
    action_button_down_short:
      - service: light.turn_off
        target:
          entity_id: light.stue_lamper
    helper_last_controller_event: input_text.stue_switch_helper
    action_button_up_long:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_step_pct: 15
    action_button_up_double:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_pct: 15
    action_button_down_long:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_step_pct: -15
    action_button_down_double:
      - service: light.turn_off
        target:
          entity_id: light.spisebords_lamper
    button_up_double_press: true
    button_down_double_press: true
    button_up_long_loop: false
    button_down_long_loop: false
    helper_double_press_delay: 1500
```

## To Reproduce\*

Steps to reproduce the issue:

3. Trigger the automation '....'

## Expected behavior\*

That long presses and double clicks fire expected actions

## Actual Behaviour\*

automation only works when removing actions for long press and double click, otherwise it results in errors

## Additional Details\*

- [x] I'd like to help developing a fix for this issue. 

## Screenshots

![Skærmbillede 2021-05-03 kl  20 37 50](https://user-images.githubusercontent.com/42773361/116918072-bee4ed80-ac4f-11eb-9e11-4331bd178524.png)

## Additional context

After browsing the repo i can't help to think it might somehow be related to #25 or [this post](https://community.home-assistant.io/t/help-needed-with-automation-and-json-template-warning/297258/13?u=bkje14) or perhaps #45

**Comment by EPMatt** [comment] 2021-05-04 08:50
Hi @bkje14, thank you for taking the time to report here.

> I had an automation configured with short, long and double clicks that have been running smoothly for weeks since i set it up.

Have you recently performed some relevant changes to your system, which might have interfered with the automation (eg. updated Zigbee2MQTT, updated the blueprint etc.)?

Moreover, just to make sure, are you running the latest version of the blueprint?
You can update the blueprint by deleting it from the Configuration->Blueprints panel, then importing it again with My Home Assistant / Direct Link from the [blueprint documentation](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1743).

Thanks!

**Comment by bkje14** [comment] 2021-05-04 17:20
Hi @EPMatt
First, a big thanks for the awsome blueprints you make! they are truly wonderful.

At first i suspected the z2m integration to be the culprit, at I did indeed have it on auto update so i recieved the newest a couple of days ago, and that could of course be the reason. However, when hooking the remote up to simpler automations there seems to be no errors occuring, which led me here. 

I just reinstalled the latest version of the blueprint at tried that. The same thing happens, no actions are performed when the double click or long press actions are configured.

Here is a z2m log of doing a short_up_press action.
It is a little hard for me to see if this is as expected or not. 
![Skærmbillede 2021-05-04 kl  18 57 47](https://user-images.githubusercontent.com/42773361/117042393-35dfbc00-ad0c-11eb-814d-784b1b81dc8f.png)

After having read a little about it I can understand that is expected that multiple events are occuring even when only doing one press. I am though a little suprised by the third having a `"action": null`

I saved the 5 automation traces that came out of that click.
[automation_trace.zip](https://github.com/EPMatt/awesome-ha-blueprints/files/6422796/automation_trace.zip)

three of them seem to be handled as expected - being supressed as not real clicks.
Two of them results in an error: 
first of the five traces:
![Skærmbillede 2021-05-04 kl  19 13 30](https://user-images.githubusercontent.com/42773361/117042940-e2ba3900-ad0c-11eb-84e3-49f28af3f194.png)

last of the five traces:
![Skærmbillede 2021-05-04 kl  19 13 46](https://user-images.githubusercontent.com/42773361/117042994-f36aaf00-ad0c-11eb-9bd4-ea3f2e8a61d2.png)

lastly, i checked the ìnput_text` for the double clicks via the developer console. 
even when the automation fails it actions the correct button click is saved in the helper. 
for long presses it stores the `brightness_move_up` and for double clicks it saves "on" for the first and clears it for the second click. 

Let me know if there is any thing I can test or check on my end, i'll be happy to help. 
I will also try and dig in and see if i have a snapshot with an older version of z2m.

Best regards,
Bjørn

**Comment by bkje14** [comment] 2021-05-04 17:49
Well, you where right in your initial assumption. 
I found a snapshot with the previous z2m version 1.18.2-1 and that solved the issue. 
Automations work as expected again.

Looking at the z2m logs, the only difference i see is this `action:null`
But i will try and ask over at the z2m repo what might be the culprit of this. 

Thank you very much for the help and time you put into this.
If you ever need someone to test new things, i would be happy to help out.

**Comment by EPMatt** [comment] 2021-05-04 21:07
Hi @bkje14, thank you for reporting and for your nice feedback.

I'm happy to hear that your issue is solved by downgrading z2m. :)
I guess the problem is that the blueprint picks the event up, and it does not filter it since `action!=""`. The issue might be with [zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters), which is the component responsible for providing device support, and not with Zigbee2MQTT itself.

> Thank you very much for the help and time you put into this.
If you ever need someone to test new things, i would be happy to help out.

Thank you, I'm glad to hear that this blueprint is useful for you. I'm planning to increase the number of supported controllers, so if you have any device which you'd like to be included in the Controllers blueprint collection please let me know.

Moreover, if you notice some PR/issue which you'd like to contribute to you can always jump into the discussion and post your opinion there. Any kind of contribution or feedback is highly appreciated. :)

Thanks again!

**Comment by EPMatt** [comment] 2021-05-09 20:41
Hi @bkje14,

I'm closing this issue since your original problem is solved. If you need any additional guidance don't hesitate to open a new issue or create a discussion, I'll be glad to help. :)

Thank you and happy automating!

**Closed by EPMatt** 2021-05-09 20:41 UTC
Labels: blueprint, bug

**Comment by bkje14** [comment] 2021-05-26 13:29
Hi @EPMatt !
That sounds great! 
I'll definitely do that later today. 
Thanks again for the effort making these blueprints (Y)
